
export const metadata = {
    title: "Tutopia - add to cart",
    description: "Generated by create next app",
};

export default function Layout({ children }) {
    return (
        <>{children}</>
    );
  }