export const metadata = {
    title: "Tutopia - products",
    description: "Generated by create next app",
};

export default function Layout({ children }) {
    return (
      <>
        {children}
      </>
    )
  }